name: 部署到 GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设置 Pages
        uses: actions/configure-pages@v3
      - name: 上传文件
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 